(function(){
const $=id=>document.getElementById(id),API='https://script.google.com/macros/s/AKfycbzq2sNhxV9PnOktzS8UUIypcvguyc58s8GMd_3D4VjSxUirx-XR-3bsC_yF9zFGNWqGww/exec';
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const cap=s=>String(s||'').trim().replace(/^./,c=>c.toUpperCase()).replace(/^Sdb\b/i,'Salle de bains');
const css=document.createElement('style');css.textContent=`
:root{--ab:#082a52;--ab2:#0d5aa7}.visit-top-actions{display:grid;grid-template-columns:1fr 1fr;gap:9px;margin-bottom:12px}.visit-top-actions .back,.visit-top-actions #finish{margin:0!important;min-height:60px!important;border-radius:18px!important}.visit-top-actions #finish{font-size:14px!important;padding:10px!important}.metric-note{margin:10px 0;padding:13px;border-radius:14px;background:#f7faff;border:1px solid #d6e5f4;font-size:14px;line-height:1.48}.metric-live{min-height:52px;display:flex;align-items:center;justify-content:center;padding:10px;border-radius:13px;background:#f5f8fb;margin-top:8px;font-size:14px;color:#42566e;text-align:center}
.ai330{background:#fff;border:1px solid #dce5ee;border-radius:22px;padding:16px;margin-bottom:12px;box-shadow:0 8px 24px #082a5210}.ai330-head{display:flex;justify-content:space-between;gap:10px;align-items:center}.ai330-title{font-size:20px;font-weight:900;color:#082a52}.ai330-badge{font-size:10px;font-weight:900;padding:6px 9px;border-radius:99px;background:#eaf2fa;color:#0d5aa7}.ai330-summary{background:linear-gradient(145deg,#082a52,#0d5aa7);color:#fff;border-radius:17px;padding:14px;margin-top:12px;line-height:1.5}.ai330-piece{border:1px solid #e0e8ef;border-radius:17px;padding:13px;margin-top:12px}.ai330-piece h3{margin:0 0 8px;color:#082a52;font-size:18px}.ai330-sec{margin-top:10px}.ai330-sec>b{display:block;font-size:12px;text-transform:uppercase;color:#627287;margin-bottom:4px}.ai330-line{padding:7px 0;border-top:1px solid #edf1f4;font-size:14px;line-height:1.42}.ai330-lots{display:grid;gap:9px;margin-top:10px}.ai330-lot{border-left:4px solid #0d5aa7;background:#f7faff;border-radius:12px;padding:11px}.ai330-lot h4{margin:0 0 6px;color:#082a52}.ai330-warn{background:#fff7e8;border:1px solid #f1d9a8;border-radius:14px;padding:12px;margin-top:10px}.ai330-actions{background:#eef7f2;border:1px solid #cfe6d9;border-radius:14px;padding:12px;margin-top:10px}.ai330-generate{width:100%;min-height:66px;background:#082a52;color:#fff;border-radius:17px;font-size:17px;margin-top:12px}.ai330-generate:disabled{opacity:.55}.v330-help{font-size:13px;color:#68788c;line-height:1.45;margin-top:7px}
`;document.head.appendChild(css);
function room(text){const m=String(text||'').replace(/[’]/g,"'").match(/(chambre(?:\s+(?:bébé|parentale|enfant|amis|invités?|[1-9]|rdc|étage))?|bureau(?:\s+(?:[1-9]|rdc|étage|principal|enfant))?|cuisine(?:\s+(?:ouverte|fermée|rdc|étage))?|salon(?:\s+(?:principal|rdc|étage))?|séjour(?:\s+(?:principal|rdc|étage))?|salle de bains?(?:\s+(?:[1-9]|rdc|étage|parents?|enfants?))?|sdb(?:\s+(?:[1-9]|rdc|étage))?|wc(?:\s+(?:[1-9]|rdc|étage))?|couloir(?:\s+(?:rdc|étage))?|entrée|garage(?:\s+(?:[1-9]|principal))?|buanderie|cellier|terrasse(?:\s+(?:avant|arrière))?|dressing|palier(?:\s+(?:rdc|étage))?|cave|combles?)/i);return m?cap(m[1]):''}
function norm(t){return String(t||'').toLowerCase().replace(/,/g,'.').replace(/virgule/g,'.').replace(/(\d+)\s*(?:m|mètre|mètres)\s*(\d{1,2})\b/g,'$1.$2m').replace(/(\d+)\s*(?:cm|centimètres?)\b/g,(_,a)=>(Number(a)/100).toFixed(2)+'m')}
function dim(v){let n=Number(v);if(n>20&&n<=500)n/=100;return n>0&&n<=30?n:0}
function obj(t){const m=String(t||'').match(/\b(mur(?:\s+(?:côté\s+)?[\wÀ-ÿ'-]+){0,3}|cloison|porte|fenêtre|verrière|ouverture|receveur|niche|placard|plan de travail|plafond|sol|façade|escalier|baie(?: vitrée)?|radiateur|meuble|douche|vasque)\b/i);return m?cap(m[1]):''}
window.roomFromText=room;window.detectMetrics=function(text){const n=norm(text),piece=room(text)||(window.S&&S.currentPiece)||'',designation=obj(text)||(piece?'Pièce':'Métré'),out=[];let m;const re=/(\d+(?:\.\d+)?)\s*(?:m|mètre|mètres)?\s*(?:par|x|fois|sur)\s*(\d+(?:\.\d+)?)\s*(?:m|mètre|mètres)?/gi;while((m=re.exec(n))){const a=dim(m[1]),b=dim(m[2]);if(a&&b)out.push({piece,designation,a,b,phrase:String(text||'')})}return out};
function ensureMetric(){const h=$('metricHero');if(!h)return;let n=$('metricOriginal');if(!n){n=document.createElement('div');n.id='metricOriginal';n.className='metric-note';h.after(n)}if($('metricVoiceText'))$('metricVoiceText').className='metric-live'}
function renderMetric(t){const txt=String(t||'').trim();if(!txt)return;ensureMetric();$('metricOriginal').innerHTML='<b>Phrase dictée associée</b><br>'+esc(txt);const m=window.detectMetrics(txt)[0],p=room(txt),o=obj(txt);$('metricVoiceText').textContent='Entendu : '+txt;if(p)$('mPiece').value=p;if(o)$('mDesignation').value=o;if(m){$('mL').value=m.a;$('mW').value=m.b;$('metricBig').textContent=Number(m.a).toFixed(2).replace('.',',')+' × '+Number(m.b).toFixed(2).replace('.',',')+' m';$('metricContext').textContent=(m.piece||'Localisation à préciser')+' · '+(m.designation||'Métré');$('metricHero').classList.remove('hidden');if(window.S)S.pendingMetric={...(S.pendingMetric||{}),...m,phrase:txt}}}
function bindMetric(){ensureMetric();const b=$('metricVoice');if(!b)return;b.onclick=function(){if(window.S&&S.metricRec){try{S.metricRec.stop()}catch{}return}const C=window.SpeechRecognition||window.webkitSpeechRecognition;if(!C)return;const r=new C;if(window.S)S.metricRec=r;r.lang='fr-FR';r.interimResults=true;r.continuous=false;let fin='',last='';b.textContent='🔴 ARRÊTER LA DICTÉE';b.style.background='#c9343d';b.style.color='#fff';$('metricVoiceText').textContent='Je vous écoute…';r.onresult=e=>{let inter='';for(let i=e.resultIndex;i<e.results.length;i++){const t=(e.results[i][0]?.transcript||'').trim();if(e.results[i].isFinal)fin=(fin+' '+t).trim();else inter=(inter+' '+t).trim()}last=(fin+' '+inter).trim();$('metricVoiceText').textContent=last?'Entendu : '+last:'Je vous écoute…';const p=room(last);if(p)$('mPiece').value=p};r.onend=()=>{if(window.S)S.metricRec=null;b.textContent='🎙️ Redicter / corriger';b.style.background='';b.style.color='';if(fin||last)renderMetric(fin||last)};try{r.start()}catch{if(window.S)S.metricRec=null}};const old=window.openMetric;if(typeof old==='function')window.openMetric=function(m){old(m);ensureMetric();const p=m&&m.phrase;$('metricOriginal').innerHTML=p?'<b>Phrase dictée associée</b><br>'+esc(p):'<b>Phrase dictée associée</b><br>Aucune phrase vocale associée.'}}
function topFinish(){const v=$('visit'),f=$('finish'),b=v&&v.querySelector('.back');if(v&&f&&b&&!v.querySelector('.visit-top-actions')){const x=document.createElement('div');x.className='visit-top-actions';b.before(x);x.appendChild(b);f.textContent='✓ TERMINER';x.appendChild(f)}}
function lines(title,a){if(!Array.isArray(a)||!a.length)return'';return '<div class="ai330-sec"><b>'+esc(title)+'</b>'+a.map(x=>'<div class="ai330-line">'+esc(x)+'</div>').join('')+'</div>'}
function renderAI(card,r){card.innerHTML='<div class="ai330-head"><div class="ai330-title">✨ Préparation du devis par IA</div><span class="ai330-badge">RELUE & STRUCTURÉE</span></div><div class="ai330-summary"><b>Synthèse du projet</b><br>'+esc(r.synthese_projet||'')+'</div>'+(r.pieces||[]).map(p=>'<div class="ai330-piece"><h3>'+esc(p.nom||'Zone')+'</h3>'+lines('Constats',p.constats)+lines('Travaux à prévoir',p.travaux)+lines('Métrés validés',p.metres)+lines('Éléments techniques',p.technique)+lines('Photos / commentaires',p.photos)+lines('Points à confirmer',p.points_a_confirmer)+'</div>').join('')+'<div class="ai330-sec"><b>Synthèse par lot pour chiffrage</b><div class="ai330-lots">'+(r.synthese_lots||[]).map(l=>'<div class="ai330-lot"><h4>'+esc(l.lot||'Lot')+'</h4>'+(l.prestations||[]).map(x=>'<div class="ai330-line">'+esc(x)+'</div>').join('')+'</div>').join('')+'</div></div>'+((r.points_a_confirmer||[]).length?'<div class="ai330-warn"><b>⚠ Points à confirmer avant devis</b>'+(r.points_a_confirmer||[]).map(x=>'<div class="ai330-line">'+esc(x)+'</div>').join('')+'</div>':'')+((r.actions_ab_renov||[]).length?'<div class="ai330-actions"><b>✓ Actions AB RENOV</b>'+(r.actions_ab_renov||[]).map(x=>'<div class="ai330-line">'+esc(x)+'</div>').join('')+'</div>':'')}
async function runAI(id,card,btn){btn.disabled=true;btn.textContent='✨ Relecture et rédaction en cours…';try{const body=new URLSearchParams({action:'generateReportAI',idRdv:id}),res=await fetch(API,{method:'POST',body}),j=await res.json();if(!j.ok)throw Error(j.error||'IA indisponible');if(j.report)renderAI(card,j.report);else card.innerHTML='<div class="ai330-title">Compte-rendu IA</div><div class="v330-help">'+esc(j.rapportComplet||'Rapport généré.')+'</div>'}catch(e){btn.disabled=false;btn.textContent='✨ Réessayer la rédaction IA';const w=document.createElement('div');w.className='ai330-warn';w.textContent=e.message;card.appendChild(w)}}
function injectAI(id){const root=$('reportContent');if(!root||root.querySelector('.ai330'))return;const c=document.createElement('div');c.className='ai330';c.innerHTML='<div class="ai330-head"><div class="ai330-title">✨ Préparation du devis par IA</div><span class="ai330-badge">RELECTURE MÉTIER</span></div><div class="v330-help">L’IA relit la dictée, corrige les erreurs évidentes, retire les répétitions, conserve les données techniques puis prépare les prestations par pièce et par lot.</div><button class="ai330-generate">✨ RELIRE ET PRÉPARER LE DEVIS</button>';const h=root.querySelector('.reportHead');h?h.after(c):root.prepend(c);const b=c.querySelector('button');b.onclick=()=>runAI(id,c,b)}
function wrapReport(){const old=window.openReport;if(typeof old!=='function'||old.__v330)return;const w=async function(id){await old(id);setTimeout(()=>injectAI(id),0)};w.__v330=true;window.openReport=w}
function boot(){const v=document.querySelector('.ver');if(v)v.textContent='V3.3.0';topFinish();bindMetric();wrapReport()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();